### ISSUE TITLE
Error in copying stop limit & take profit limit orders

### ISSUE THREAD

**Issue by tolgamorf** [destructiondogo/bitmex-copy-bot#3]
Below is the error message when trying to copy a **stop _limit_** or a **take profit _limit_** order.
```
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    run()
  File "run.py", line 60, in run
    execution['side'], execution['orderID'],execution['execInst'],execution['pegPriceType'],execution['pegOffsetValue'])
  File "bitmex_api.py", line 53, in wrapped
    return function(self, *args, **kwargs)
  File "bitmex_api.py", line 116, in place_order_stop
    return self._curl_bitmex(api=endpoint, postdict=postdict, verb="POST")
  File "bitmex_api.py", line 233, in _curl_bitmex
    raise e
  File "bitmex_api.py", line 169, in _curl_bitmex
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order
Exception ignored in: <function BitMEX.__del__ at 0x103f29c20>
```

The rest of the error is related to another issue. (#2)
```
Traceback (most recent call last):
  File "bitmex_api.py", line 40, in __del__
    self.exit()
  File "bitmex_api.py", line 43, in exit
    self.ws.exit()
AttributeError: 'BitMEX' object has no attribute 'ws'
```

**Comment by bhageshvar** [comment]
Install this repo. If this works it should probably solve all your other problems. 
https://pypi.org/project/bitmex-ws-onix/
