### ISSUE TITLE
Websockets disconnects every few minutes

### ISSUE THREAD

**Issue by gitroli** [destructiondogo/bitmex-copy-bot#7]
Websockets disconnects every few minutes, I need help please

**Comment by gitroli** [comment]
Here are details:
C:\bitmex-copy-bot-master>python run.py
2020-02-18 11:43:16,127 - root - INFO - >>> Starting BitMEX COPY BOT...
2020-02-18 11:43:16,127 - bitmex_websocket - INFO - Connecting to wss://www.bitmex.com/realtime?subscribe=execution:,margin
2020-02-18 11:43:16,127 - bitmex_websocket - INFO - Authenticating with API Key.
2020-02-18 11:43:17,139 - bitmex_websocket - INFO - Connected to WS.
2020-02-18 11:46:16,382 - bitmex_websocket - ERROR - Error : Connection is already closed.
2020-02-18 11:46:16,382 - websocket - ERROR - error from callback <bound method BitMEXWebsocket.__on_error of <bitmex_websocket.BitMEXWebsocket object at 0x0000021FCDD83DC0>>: Connection is already closed.
2020-02-18 11:46:16,382 - bitmex_websocket - INFO - Websocket Closed
2020-02-18 11:46:17,201 - root - ERROR - 'NoneType' object has no attribute 'connected'
Traceback (most recent call last):
  File "run.py", line 102, in main
    run()
  File "run.py", line 40, in run
    if ws[ws_leader].ws.sock.connected:
AttributeError: 'NoneType' object has no attribute 'connected'
2020-02-18 11:46:17,201 - root - INFO - >>> Error occurred. The bot will restart in 5 seconds...
2020-02-18 11:46:22,204 - root - INFO - >>> Starting BitMEX COPY BOT...
2020-02-18 11:46:22,204 - bitmex_websocket - INFO - Connecting to wss://www.bitmex.com/realtime?subscribe=execution:,margin
2020-02-18 11:46:22,204 - bitmex_websocket - INFO - Authenticating with API Key.
2020-02-18 11:46:23,219 - bitmex_websocket - INFO - Connected to WS.

**Comment by gitroli** [comment]
Here is error message from your version, other error messages is from tolgamorf:

python run.py
2020-02-18 12:05:32,371 - bitmex_websocket - INFO - Connecting to wss://www.bitmex.com/realtime?subscribe=execution:,instrument:,order:,orderBookL2:,position:,quote:,trade:,margin
2020-02-18 12:05:32,371 - bitmex_websocket - INFO - Authenticating with API Key.
2020-02-18 12:05:33,388 - bitmex_websocket - INFO - Connected to WS.
2020-02-18 12:05:41,435 - bitmex_websocket - INFO - Got all market data. Starting.
2020-02-18 12:05:41,451 - root - INFO - Instrument data: {'symbol': '.EVOL7D', 'rootSymbol': 'EVOL', 'state': 'Unlisted', 'typ': 'MRIXXX', 'listing': None, 'front': None, 'expiry': None, 'settle': None, 'relistInterval': None, 'inverseLeg': '', 'sellLeg': '', 'buyLeg': '', 'optionStrikePcnt': None, 'optionStrikeRound': None, 'optionStrikePrice': None, 'optionMultiplier': None, 'positionCurrency': '', 'underlying': 'ETH', 'quoteCurrency': 'XXX', 'underlyingSymbol': '.EVOL7D', 'reference': 'BMEX', 'referenceSymbol': '.BETHXBT', 'calcInterval': '2000-01-08T00:00:00.000Z', 'publishInterval': '2000-01-01T00:05:00.000Z', 'publishTime': None, 'maxOrderQty': None, 'maxPrice': None, 'lotSize': None, 'tickSize': 0.01, 'multiplier': None, 'settlCurrency': '', 'underlyingToPositionMultiplier': None, 'underlyingToSettleMultiplier': None, 'quoteToSettleMultiplier': None, 'isQuanto': False, 'isInverse': False, 'initMargin': None, 'maintMargin': None, 'riskLimit': None, 'riskStep': None, 'limit': None, 'capped': False, 'taxed': False, 'deleverage': False, 'makerFee': None, 'takerFee': None, 'settlementFee': None, 'insuranceFee': None, 'fundingBaseSymbol': '', 'fundingQuoteSymbol': '', 'fundingPremiumSymbol': '', 'fundingTimestamp': None, 'fundingInterval': None, 'fundingRate': None, 'indicativeFundingRate': None, 'rebalanceTimestamp': None, 'rebalanceInterval': None, 'openingTimestamp': None, 'closingTimestamp': None, 'sessionInterval': None, 'prevClosePrice': None, 'limitDownPrice': None, 'limitUpPrice': None, 'bankruptLimitDownPrice': None, 'bankruptLimitUpPrice': None, 'prevTotalVolume': None, 'totalVolume': None, 'volume': None, 'volume24h': None, 'prevTotalTurnover': None, 'totalTurnover': None, 'turnover': None, 'turnover24h': None, 'homeNotional24h': None, 'foreignNotional24h': None, 'prevPrice24h': 9.96, 'vwap': None, 'highPrice': None, 'lowPrice': None, 'lastPrice': 10.64, 'lastPriceProtected': None, 'lastTickDirection': 'ZeroPlusTick', 'lastChangePcnt': 0.0683, 'bidPrice': None, 'midPrice': None, 'askPrice': None, 'impactBidPrice': None, 'impactMidPrice': None, 'impactAskPrice': None, 'hasLiquidity': False, 'openInterest': None, 'openValue': 0, 'fairMethod': '', 'fairBasisRate': None, 'fairBasis': None, 'fairPrice': None, 'markMethod': 'LastPrice', 'markPrice': 10.64, 'indicativeTaxRate': None, 'indicativeSettlePrice': None, 'optionUnderlyingPrice': None, 'settledPrice': None, 'timestamp': '2020-02-18T10:50:00.000Z', 'tickLog': 2}
2020-02-18 12:19:11,418 - bitmex_websocket - ERROR - Error : [WinError 10054] An existing connection was forcibly closed by the remote host
2020-02-18 12:19:11,418 - websocket - ERROR - error from callback <bound method BitMEXWebsocket.__on_error of <bitmex_websocket.BitMEXWebsocket object at 0x0000028D72224D90>>: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-02-18 12:19:11,418 - bitmex_websocket - INFO - Websocket Closed
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    run()
  File "run.py", line 40, in run
    if ws[ws_leader].ws.sock.connected:
AttributeError: 'NoneType' object has no attribute 'connected'
Exception ignored in: <function BitMEX.__del__ at 0x0000028D72227820>
Traceback (most recent call last):
  File "C:\bitmex-copy-bot-master-original\bitmex_api.py", line 40, in __del__
    self.exit()
  File "C:\bitmex-copy-bot-master-original\bitmex_api.py", line 43, in exit
    self.ws.exit()
AttributeError: 'BitMEX' object has no attribute 'ws'
